// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/order-engine/order-engine.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderEngine_Reserve_FullMethodName = "/order.OrderEngine/Reserve"
	OrderEngine_Release_FullMethodName = "/order.OrderEngine/Release"
)

// OrderEngineClient is the client API for OrderEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderEngineClient interface {
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
}

type orderEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderEngineClient(cc grpc.ClientConnInterface) OrderEngineClient {
	return &orderEngineClient{cc}
}

func (c *orderEngineClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, OrderEngine_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderEngineClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, OrderEngine_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderEngineServer is the server API for OrderEngine service.
// All implementations must embed UnimplementedOrderEngineServer
// for forward compatibility.
type OrderEngineServer interface {
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	mustEmbedUnimplementedOrderEngineServer()
}

// UnimplementedOrderEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderEngineServer struct{}

func (UnimplementedOrderEngineServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedOrderEngineServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedOrderEngineServer) mustEmbedUnimplementedOrderEngineServer() {}
func (UnimplementedOrderEngineServer) testEmbeddedByValue()                     {}

// UnsafeOrderEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderEngineServer will
// result in compilation errors.
type UnsafeOrderEngineServer interface {
	mustEmbedUnimplementedOrderEngineServer()
}

func RegisterOrderEngineServer(s grpc.ServiceRegistrar, srv OrderEngineServer) {
	// If the following call pancis, it indicates UnimplementedOrderEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderEngine_ServiceDesc, srv)
}

func _OrderEngine_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEngineServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEngine_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEngineServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderEngine_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEngineServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEngine_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEngineServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderEngine_ServiceDesc is the grpc.ServiceDesc for OrderEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderEngine",
	HandlerType: (*OrderEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _OrderEngine_Reserve_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _OrderEngine_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/order-engine/order-engine.proto",
}
