// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: proto/shipping-engine/shipping-engine.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShippingId    string                 `protobuf:"bytes,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

type HoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShippingId    string                 `protobuf:"bytes,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldRequest) Reset() {
	*x = HoldRequest{}
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRequest) ProtoMessage() {}

func (x *HoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRequest.ProtoReflect.Descriptor instead.
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP(), []int{2}
}

func (x *HoldRequest) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

type HoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldResponse) Reset() {
	*x = HoldResponse{}
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldResponse) ProtoMessage() {}

func (x *HoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldResponse.ProtoReflect.Descriptor instead.
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP(), []int{3}
}

type RetractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractRequest) Reset() {
	*x = RetractRequest{}
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractRequest) ProtoMessage() {}

func (x *RetractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractRequest.ProtoReflect.Descriptor instead.
func (*RetractRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP(), []int{4}
}

func (x *RetractRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type RetractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractResponse) Reset() {
	*x = RetractResponse{}
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractResponse) ProtoMessage() {}

func (x *RetractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_engine_shipping_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractResponse.ProtoReflect.Descriptor instead.
func (*RetractResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP(), []int{5}
}

var File_proto_shipping_engine_shipping_engine_proto protoreflect.FileDescriptor

var file_proto_shipping_engine_shipping_engine_proto_rawDesc = string([]byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x0f, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x10, 0x44,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x64,
	0x22, 0x2e, 0x0a, 0x0b, 0x48, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x64,
	0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x11, 0x0a,
	0x0f, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x8e, 0x01, 0x0a, 0x08, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x2f, 0x0a,
	0x08, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x2e, 0x44, 0x69, 0x73, 0x70,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x04, 0x48, 0x6f, 0x6c, 0x64, 0x12, 0x0c, 0x2e, 0x48, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x48, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x0f,
	0x2e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x6b, 0x6c, 0x72, 0x73, 0x6e, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x64, 0x65, 0x66, 0x73,
	0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x3b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_shipping_engine_shipping_engine_proto_rawDescOnce sync.Once
	file_proto_shipping_engine_shipping_engine_proto_rawDescData []byte
)

func file_proto_shipping_engine_shipping_engine_proto_rawDescGZIP() []byte {
	file_proto_shipping_engine_shipping_engine_proto_rawDescOnce.Do(func() {
		file_proto_shipping_engine_shipping_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipping_engine_shipping_engine_proto_rawDesc), len(file_proto_shipping_engine_shipping_engine_proto_rawDesc)))
	})
	return file_proto_shipping_engine_shipping_engine_proto_rawDescData
}

var file_proto_shipping_engine_shipping_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_shipping_engine_shipping_engine_proto_goTypes = []any{
	(*DispatchRequest)(nil),  // 0: DispatchRequest
	(*DispatchResponse)(nil), // 1: DispatchResponse
	(*HoldRequest)(nil),      // 2: HoldRequest
	(*HoldResponse)(nil),     // 3: HoldResponse
	(*RetractRequest)(nil),   // 4: RetractRequest
	(*RetractResponse)(nil),  // 5: RetractResponse
}
var file_proto_shipping_engine_shipping_engine_proto_depIdxs = []int32{
	0, // 0: Shipping.Dispatch:input_type -> DispatchRequest
	2, // 1: Shipping.Hold:input_type -> HoldRequest
	4, // 2: Shipping.Retract:input_type -> RetractRequest
	1, // 3: Shipping.Dispatch:output_type -> DispatchResponse
	3, // 4: Shipping.Hold:output_type -> HoldResponse
	5, // 5: Shipping.Retract:output_type -> RetractResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shipping_engine_shipping_engine_proto_init() }
func file_proto_shipping_engine_shipping_engine_proto_init() {
	if File_proto_shipping_engine_shipping_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipping_engine_shipping_engine_proto_rawDesc), len(file_proto_shipping_engine_shipping_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipping_engine_shipping_engine_proto_goTypes,
		DependencyIndexes: file_proto_shipping_engine_shipping_engine_proto_depIdxs,
		MessageInfos:      file_proto_shipping_engine_shipping_engine_proto_msgTypes,
	}.Build()
	File_proto_shipping_engine_shipping_engine_proto = out.File
	file_proto_shipping_engine_shipping_engine_proto_goTypes = nil
	file_proto_shipping_engine_shipping_engine_proto_depIdxs = nil
}
